# ?? ?? ??
spring.config.import=optional:dotenv:.env.local

# Server Settings
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DATASOURCE_URL}/dolpin
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GCS
gcs.bucket-name=${GCS_NAME}
gcs.custom-domain=${CDN_NAME}
gcs.credentials-path=${GCS_CREDENTIAL_PATH}
storage.provider=gcs

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=3000ms

# Redis Connection Pool
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.time-between-eviction-runs=30s

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false
